// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ycrwJDIPzQpXHdZi_shJz4mENZCr11I',
    appId: '1:342556620800:web:4241962d23c416c9be40e5',
    messagingSenderId: '342556620800',
    projectId: 'medification-acd45',
    authDomain: 'medification-acd45.firebaseapp.com',
    storageBucket: 'medification-acd45.firebasestorage.app',
    measurementId: 'G-YWW6SCCRVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLBzcWOpcKu3RcbdvwAzlCwZ19k_QWEKc',
    appId: '1:342556620800:android:e8eb209c9501b477be40e5',
    messagingSenderId: '342556620800',
    projectId: 'medification-acd45',
    storageBucket: 'medification-acd45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9lpPdwnVRXRxbUbBRnnaGS_F6ONrm_vo',
    appId: '1:342556620800:ios:e7ca4b5564c9f111be40e5',
    messagingSenderId: '342556620800',
    projectId: 'medification-acd45',
    storageBucket: 'medification-acd45.firebasestorage.app',
    iosBundleId: 'com.example.medification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9lpPdwnVRXRxbUbBRnnaGS_F6ONrm_vo',
    appId: '1:342556620800:ios:e7ca4b5564c9f111be40e5',
    messagingSenderId: '342556620800',
    projectId: 'medification-acd45',
    storageBucket: 'medification-acd45.firebasestorage.app',
    iosBundleId: 'com.example.medification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ycrwJDIPzQpXHdZi_shJz4mENZCr11I',
    appId: '1:342556620800:web:f02f3678d242e6dcbe40e5',
    messagingSenderId: '342556620800',
    projectId: 'medification-acd45',
    authDomain: 'medification-acd45.firebaseapp.com',
    storageBucket: 'medification-acd45.firebasestorage.app',
    measurementId: 'G-KE5HKXGTEK',
  );
}
